agent_name: spl_contract_aea
author: dassy23
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.24.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/ledger:0.19.0:bafybeift7fx4vp2jq4btplocifby2xnnbzxppxdttgyyvwepj5cv7akfom
contracts:
- dassy23/spl_token_program:0.1.0:bafybeihobcqkr3sitvzfmhmqkjfr37rvijewy3tezbvoia46exfntfygxm
protocols:
- fetchai/default:1.0.0
- fetchai/fipa:1.0.0
- open_aea/signing:1.0.0:bafybeiambqptflge33eemdhis2whik67hjplfnqwieoa6wblzlaf7vuo44
- valory/contract_api:1.0.0:bafybeiaxbrvgtbdrh4lslskuxyp4awyr4whcx3nqq5yrr6vimzsxg5dy64
- valory/ledger_api:1.0.0:bafybeih7rhi5zvfvwakx5ifgxsz2cfipeecsh7bm3gnudjxtvhrygpcftq
skills:
- dassy23/spl_token_skill:0.1.0:bafybeierif3iblmqhv75rktsxfzk6np26j7tygvj3d67d3uxsxtiybfiqq
default_ledger: solana
required_ledgers:
- solana
default_routing: {}
connection_private_key_paths: {}
private_key_paths:
  solana: solana_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-solana:
    version: ==1.24.7
default_connection: null
